version = 0.1
[default.deploy.parameters]
stack_name = "sam-app2"
resolve_s3 = true
s3_prefix = "sam-app2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "TableLocations=\"location\" TableBooks=\"book\""
image_repositories = []
